[package]
name = "quiche-jni"
version = "0.1.0"
authors = ["Oleksii Kachaiev", "Tobias Hotz"]
edition = "2018"

[dependencies]
jni = "0.19.0"
quiche = "0.9.0"
env_logger = "0.7.1"

[lib]
crate_type = ["cdylib"]
